name: beta

on:
  push:
    branches:
      - master
  workflow_dispatch: { }

jobs:
  android:
    name: Build Beta APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Decode Keystore
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
        run: echo "$KEYSTORE_FILE" | base64 --decode > $GITHUB_WORKSPACE/keystore.jks

      - name: Decode GitHub Token
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "$GITHUB_TOKEN" | base64 --decode > $GITHUB_WORKSPACE/ # a

      - name: Grant execute permissions to Gradle wrapper
        run: chmod +x gradlew

      - name: Build Beta APK
        run: |
          ./gradlew assembleBeta \
          -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/keystore.jks \
          -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
          -Pandroid.injected.signing.key.alias=key0 \
          -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Upload Beta APK
        uses: actions/upload-artifact@v4
        with:
          name: beta-apk
          path: app/build/outputs/apk/beta/app-beta.apk

      - name: Upload to Release Action
  # You may pin to the exact commit or the version.
  # uses: Shopify/upload-to-release@c77c9b3e5d288adaef98a7007bf92340ec6ce03b
  uses: Shopify/upload-to-release@v2.0.0
  with:
    name: beta-apk
    path: app/build/outputs/apk/beta/app-beta.apk
    content-type:
    repo-token: ${{ secrets.GITHUB_TOKEN }}
          
